# Generated by Django 4.0.1 on 2022-08-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='alt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='توضیح عکس'),
        ),
    ]
