# Generated by Django 4.0.1 on 2022-08-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_answer_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='alt',
            field=models.CharField(blank=True, default='insurance', max_length=50, null=True, verbose_name='توضیح عکس'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='answer/%Y/%m/%d', verbose_name='آپلود فایل'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1, verbose_name='وضعیت'),
        ),
    ]
