# Generated by Django 3.2.9 on 2022-02-10 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 22, 22, 32, 599850, tzinfo=utc)),
        ),
    ]
