# Generated by Django 4.0.1 on 2022-09-13 09:28

from django.db import migrations, models
import painless.models.validations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[painless.models.validations.validate_postal_code], verbose_name='کد پستی'),
        ),
    ]
