# Generated by Django 4.0.1 on 2022-08-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='لینکدین'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='واتس آپ'),
        ),
    ]
