# Generated by Django 4.0.1 on 2022-09-13 14:20

from django.db import migrations, models
import painless.models.validations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[painless.models.validations.validate_national_code], verbose_name='کد ملی'),
        ),
    ]
