# Generated by Django 4.0.1 on 2022-02-13 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 2, 44, 49, 693463, tzinfo=utc)),
        ),
    ]
