# Generated by Django 4.0.1 on 2022-10-27 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_remove_new_views_new_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='viewers',
            field=models.ManyToManyField(editable=False, related_name='viewed_news', to=settings.AUTH_USER_MODEL, verbose_name='بازدید'),
        ),
    ]
