# Generated by Django 4.0.1 on 2022-10-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_new_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='viewers',
        ),
        migrations.AddField(
            model_name='new',
            name='views',
            field=models.IntegerField(default=0, verbose_name='بازدید'),
        ),
    ]
