# Generated by Django 4.0.1 on 2022-09-29 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfeedback',
            name='summary',
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='role',
            field=models.CharField(default=datetime.datetime(2022, 9, 29, 0, 18, 0, 590782), max_length=128, verbose_name='سمت'),
            preserve_default=False,
        ),
    ]
