# Generated by Django 4.0.1 on 2022-09-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_customerfeedback_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerfeedback',
            options={'get_latest_by': ['-published_at'], 'ordering': ['-published_at', 'first_name'], 'verbose_name': 'فیدبک', 'verbose_name_plural': 'فیدبکها'},
        ),
        migrations.RemoveField(
            model_name='customerfeedback',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='customerfeedback',
            name='title',
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m/%d', verbose_name='تصویر'),
        ),
    ]
