# Generated by Django 4.0.1 on 2022-08-05 08:11

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetters',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=128, validators=[django.core.validators.EmailValidator()], verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'خبر نامه',
                'verbose_name_plural': 'خبر نامه ها',
                'ordering': ['email'],
            },
        ),
    ]
