# Generated by Django 4.0.1 on 2022-08-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_alter_newsletter_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['subscriber'], 'verbose_name': 'خبر نامه', 'verbose_name_plural': 'خبر نامه ها'},
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='subscriber',
        ),
    ]
