# Generated by Django 4.0.1 on 2022-07-31 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_content_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'get_latest_by': ['-created'], 'ordering': ['-created', 'subject'], 'verbose_name': 'تماس', 'verbose_name_plural': 'تماسها'},
        ),
    ]
