# Generated by Django 3.2.9 on 2022-02-14 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_category_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 12, 46, 29, 862791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 12, 46, 29, 862791, tzinfo=utc)),
        ),
    ]
