# Generated by Django 4.0.1 on 2022-02-21 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_alter_category_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
