# Generated by Django 4.0.1 on 2022-07-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_alter_category_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=128, unique_for_month='published_at', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='must be unique', max_length=128, unique_for_month='published_at', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.CharField(max_length=128, unique_for_month='published_at', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(help_text='must be unique', max_length=128, unique_for_month='published_at', verbose_name='title'),
        ),
    ]
