# Generated by Django 4.0.1 on 2022-08-20 19:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_alter_category_status_alter_subcategory_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندیها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, upload_to='category/%Y/%m/%d', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='banner',
            field=models.ImageField(blank=True, upload_to='subcategory/%Y/%m/%d', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='پیام'),
        ),
    ]
