# Generated by Django 4.0.1 on 2022-08-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_alter_category_options_alter_category_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ایکن'),
        ),
    ]
