# Generated by Django 4.0.1 on 2022-07-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0013_alter_tag_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created'], 'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسبها'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=128, unique_for_month='published_at', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(help_text='must be unique', max_length=128, unique_for_month='published_at', verbose_name='title'),
        ),
    ]
