# Generated by Django 4.0.1 on 2022-08-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0016_alter_tag_created_alter_tag_published_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1, verbose_name='وضعیت'),
        ),
    ]
