# Generated by Django 4.0.1 on 2022-08-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0017_alter_tag_options_alter_tag_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created'], 'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسبها'},
        ),
    ]
