# Generated by Django 4.0.1 on 2022-09-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
