# Generated by Django 3.2.9 on 2022-02-01 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 1, 10, 28, 28, 1233, tzinfo=utc)),
        ),
    ]
