# Generated by Django 4.0.1 on 2022-02-13 07:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 7, 51, 24, 588535, tzinfo=utc)),
        ),
    ]
