# Generated by Django 4.0.1 on 2022-07-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['-published_at'], 'ordering': ['-published_at', 'title'], 'verbose_name': 'پست', 'verbose_name_plural': 'پستها'},
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=128, unique_for_month='published_at', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='must be unique', max_length=128, unique_for_month='published_at', verbose_name='title'),
        ),
    ]
