# Generated by Django 4.0.1 on 2022-07-31 13:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='status')),
                ('subtitle', models.CharField(blank=True, max_length=128, null=True, verbose_name='متن زیرین')),
                ('summary', models.CharField(max_length=128, verbose_name='خلاصه')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='about/%Y/%m/%d')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'درباره ما ',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(help_text='must be unique', max_length=128, unique_for_month='published_at', verbose_name='title')),
                ('slug', models.CharField(max_length=128, unique_for_month='published_at', verbose_name='slug')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='status')),
                ('about', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aboutus.about')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم ما',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='status')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='تلفن')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='memnber/%Y/%m/%d')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='واتس آپ')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='پیام')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aboutus.team')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'اعضاًٰٰ\u200c',
            },
        ),
    ]
