# Generated by Django 4.0.1 on 2022-07-24 12:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(help_text='must be unique', max_length=128, unique_for_month='published_at')),
                ('slug', models.CharField(max_length=128, unique_for_month='published_at')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('subtitle', models.CharField(blank=True, max_length=128, null=True, verbose_name='subtitle')),
                ('summary', models.CharField(max_length=128, verbose_name='summary')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='about/%Y/%m/%d')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content')),
            ],
            options={
                'verbose_name': 'about us',
                'verbose_name_plural': 'about us',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(help_text='must be unique', max_length=128, unique_for_month='published_at')),
                ('slug', models.CharField(max_length=128, unique_for_month='published_at')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('about', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aboutus.about')),
            ],
            options={
                'verbose_name': 'ُteam',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('fisrt_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='firt_name')),
                ('last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='phone')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='memnber/%Y/%m/%d')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='whatsapp')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='linkedin')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aboutus.team')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
    ]
