# Generated by Django 4.0.1 on 2022-07-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.CharField(max_length=128, unique_for_month='published_at', verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(help_text='متن منحصر به فرد باید باشد', max_length=128, unique_for_month='published_at', verbose_name='متن'),
        ),
    ]
