# Generated by Django 4.0.1 on 2022-07-31 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_alter_about_status_alter_member_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='about',
            name='slug',
            field=models.CharField(default=datetime.datetime(2022, 7, 31, 19, 10, 14, 550152), max_length=128, unique_for_month='published_at', verbose_name='اسلاگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default=datetime.datetime(2022, 7, 31, 19, 10, 28, 924883), help_text='متن منحصر به فرد باید باشد', max_length=128, unique_for_month='published_at', verbose_name='متن'),
            preserve_default=False,
        ),
    ]
