# Generated by Django 4.0.1 on 2022-07-31 20:44

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_remove_about_subtitle_about_slug_about_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='about',
        ),
        migrations.AddField(
            model_name='team',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='پیام'),
        ),
        migrations.AddField(
            model_name='team',
            name='summary',
            field=models.CharField(default=datetime.datetime(2022, 7, 31, 20, 44, 29, 251352), max_length=128, verbose_name='خلاصه'),
            preserve_default=False,
        ),
    ]
