# Generated by Django 4.0.1 on 2022-08-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_remove_team_about_team_content_team_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
