# Generated by Django 4.0.1 on 2022-09-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='banner',
        ),
    ]
