# Generated by Django 4.0.1 on 2022-08-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_alter_slider_created_alter_slider_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1, verbose_name='وضعیت'),
        ),
    ]
